Update readme with full stack instructions
Jim-Hodapp-Coaching/ambi-fe pull request #11
Opened 2023-04-28 01:51 UTC by qafui

## Description
Updates the readme for a beginner audience

#### GitHub Issue: Closes #10 

### Changes
* Update quickstart guide and link to mock client and server values.

2023-04-28 02:25 UTC, jhodapp commented on README.md
> +## Running the Mock-Client
```suggestion
## Running the Ambi Mock Client to generate fake sensor values
```

2023-04-28 02:28 UTC, jhodapp requested changes
Looks great @qafui, I have a couple of minor suggestions.

2023-04-28 02:28 UTC, jhodapp commented on docs/sequence-front-end.png
This looks great @qafui! One suggestion is, in the "Ambi Mock Client" block, to mention "Edge HW Client / Ambi Mock Client". My suggestion just points out that the mock client or a real hardware client "i.e. embedded Rust application and real sensor hardware" can provide the input sensor values into the system.

2023-05-25 21:04 UTC, qafui commented on docs/sequence-front-end.png
Makes sense. Thanks.

2023-05-26 00:10 UTC, jhodapp approved these changes
Looks great, thank you David.

2023-05-26 00:23 UTC, calebbourg approved these changes

2023-05-26 00:29 UTC, merged