Adds github unit-test workflow
Jim-Hodapp-Coaching/ambi-fe pull request #6
Opened 2023-03-03 02:46 UTC by qafui

# Summary
Runs unit tests with a GitHub action

Closes #4

2023-03-04 17:49 UTC, jhodapp requested changes
Just a minor suggested change, looks good David, thank you!

2023-03-04 17:49 UTC, jhodapp commented on .github/workflows/unit-tests.yml
> +    runs-on: 'ubuntu-latest'
```suggestion
    runs-on: ubuntu-22.04
```

2023-03-04 17:49 UTC, jhodapp commented on .github/workflows/unit-tests.yml
> +    runs-on: 'ubuntu-latest'
We use this specific LTS version of Ubuntu for the `ambi-rs` repo, so I think it's helpful to use the same version across the project.

2023-03-07 02:51 UTC, qafui commented
> Just a minor suggested change, looks good David, thank you!

Thank you! Ready to merge!

2023-03-07 16:44 UTC, jhodapp approved these changes
Looks fantastic, thank you David!

2023-03-09 23:46 UTC, merged